In [13]:
#Introduction To NumPy

In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
data= np.random.randn(2,2)

In [5]:
data

array([[-1.40186667, -1.32697708],
       [-0.04346928, -0.1991845 ]])

In [6]:
data*3

array([[-4.20560001, -3.98093124],
       [-0.13040784, -0.59755351]])

In [7]:
data+data

array([[-2.80373334, -2.65395416],
       [-0.08693856, -0.39836901]])

In [8]:
data.shape

(2, 2)

In [9]:
data.dtype

dtype('float64')

In [10]:
a=[1,2,3,4]


In [11]:
arr1=np.array(a)
arr1

array([1, 2, 3, 4])

In [12]:
b=[[1,2,3,4],[5,6,7,8],[9,2,4,2]]

In [13]:
arr2=np.array(b)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 2, 4, 2]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(3, 4)

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.19757059e-321],
       [7.56592337e-307, 9.34588060e-307, 3.62651150e-317]])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [25]:
np.ones_like((2,2))

array([1, 1])

In [2]:
import numpy as np
arr1=np.array([1,2,3,4],dtype=np.float64)

In [3]:
arr1.dtype

dtype('float64')

In [4]:
arr1.astype(np.int32)

array([1, 2, 3, 4])

In [5]:
arr1.dtype

dtype('float64')

In [6]:
arr= np.array([1,2,3,4])


In [7]:
arr.dtype

dtype('int32')

In [8]:
b= arr.astype(np.float64)


In [9]:
b.dtype

dtype('float64')

In [11]:
f= np.array([1.2,1.4,3.55,23.3,34.22])
f

array([ 1.2 ,  1.4 ,  3.55, 23.3 , 34.22])

In [12]:
f.astype(np.int32)

array([ 1,  1,  3, 23, 34])

In [14]:
#Arthmetic Operations


In [17]:
a= np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
b=np.array([[[2,35,4,3],[2,4,54,32]]])
b

array([[[ 2, 35,  4,  3],
        [ 2,  4, 54, 32]]])

In [19]:
c=a+b

In [20]:
c

array([[[ 3, 37,  7,  7],
        [ 7, 10, 61, 40]]])

In [21]:
d=a-b
d

array([[[ -1, -33,  -1,   1],
        [  3,   2, -47, -24]]])

In [22]:
d=a*b
d

array([[[  2,  70,  12,  12],
        [ 10,  24, 378, 256]]])

In [23]:
e=a**b

In [24]:
e

array([[[          1,           0,          81,          64],
        [         25,        1296, -2061349871,           0]]])

In [25]:
a>b

array([[[False, False, False,  True],
        [ True,  True, False, False]]])

In [26]:
#Basic Indexing and Slicing

In [30]:
array=([1,2,34,4,5,67,3,22,11,5])
array


[1, 2, 34, 4, 5, 67, 3, 22, 11, 5]

In [32]:
#accessing element in index 4 
array[4]

5

In [42]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
#slicing 
arr[5:8]

array([5, 6, 7])

In [47]:
arr[5:8] =11
arr

array([ 0,  1,  2,  3,  4, 11, 11, 11,  8,  9])

In [49]:
slice= arr[5:8]
slice

array([11, 11, 11])

In [54]:
slice[2]=123456
slice


array([    11, 123456, 123456])

In [56]:
#bare slicing
slice[:]=123
arr

array([  0,   1,   2,   3,   4, 123, 123, 123,   8,   9])

In [58]:
#Indexing and slicing in Two Dimensional Array
arr=np.array([[1,2],[3,4],[5,6],[7,8]])
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [59]:
arr[3]

array([7, 8])

In [62]:
#accesing specific element 
arr[1,1]


4