In [1]:
#Linear Algebra With Numpy

In [2]:
import numpy as np


In [7]:
#Creating Scalar
a= 5
a

5

In [11]:
#Checking type(list or array?)
z=[1,2]
print(type(z))

<class 'list'>


In [14]:
s=np.array(z)
print(type(s))

<class 'numpy.ndarray'>


In [17]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr1= np.array([[2,4,5],[4,5,6],[3,6,8]])
arr1

array([[2, 4, 5],
       [4, 5, 6],
       [3, 6, 8]])

In [19]:
#Adding Matrices

In [21]:
add = arr + arr1
print("Addition : ", add)

Addition :  [[ 3  6  8]
 [ 8 10 12]
 [10 14 17]]


In [22]:
#Subtraction 
sub = arr - arr1
print("Subtraction: ", sub)

Subtraction:  [[-1 -2 -2]
 [ 0  0  0]
 [ 4  2  1]]


In [27]:
# Multiplication 
print(np.dot(arr,arr1))

[[ 19  32  41]
 [ 46  77  98]
 [ 73 122 155]]


In [9]:
#Multiplication using matmul
arr= np.array([[1,2,3],[4,3,45],[2,4,5,]])
arr1= np.array([[3,55,6],[3,34,53],[3,5,63]])
mul=np.matmul(arr,arr1)
print(mul)

[[  18  138  301]
 [ 156  547 3018]
 [  33  271  539]]


In [28]:
#Multiplication with Scalar
arr *2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
#Determinant 
a=[[1,2],[2,5]]
print(np.linalg.det(a))


1.0


In [32]:
#Transpose
print(np.transpose(arr))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [33]:
#Inverse
print(np.linalg.inv(a))

[[ 5. -2.]
 [-2.  1.]]


In [34]:
#Rank
print(np.linalg.matrix_rank(arr))

2


In [20]:
#Statistics with NumPy

In [10]:
import numpy as np
import statistics

In [11]:
arr=np.array([1,2,3,4,5,23,34,21])
arr

array([ 1,  2,  3,  4,  5, 23, 34, 21])

In [12]:
#Mean
print("Mean of arr :", statistics.mean(arr))

Mean of arr : 11


In [13]:
#Median 
print(statistics.median(arr))

4.5


In [14]:
#Median low
print(statistics.median_low(arr))

4


In [15]:
#Median High
print(statistics.median_high(arr))

5


In [16]:
#Mode
print(statistics.mode(arr))

1


In [17]:
#Variance
print(statistics.variance(arr))

157


In [18]:
#standard deviation 
print(statistics.stdev(arr))

12.529964086141668


In [19]:
#Range (Range = Max value - Min value)
maximum =  max(arr)
minimum = min(arr)
print("Maximum : ", maximum)
print("Minimum : ", minimum )
range =maximum -  minimum
print(range)

Maximum :  34
Minimum :  1
33
