In [ ]:
#Series and DataFrames

In [3]:
import pandas as pd
from pandas import Series

In [8]:
obj = pd.Series([12,23,4,2,12,4])
obj


0    12
1    23
2     4
3     2
4    12
5     4
dtype: int64

In [9]:
obj.values

array([12, 23,  4,  2, 12,  4], dtype=int64)

In [10]:
obj.index

RangeIndex(start=0, stop=6, step=1)

In [15]:
obj2 =pd.Series([12,3,4,2],index=['e','b','s','w'])
obj2

e    12
b     3
s     4
w     2
dtype: int64

In [16]:
obj2 .index

Index(['e', 'b', 's', 'w'], dtype='object')

In [18]:
obj2.values

array([12,  3,  4,  2], dtype=int64)

In [21]:
'm' in obj2

False

In [22]:
'b' in obj2

True

In [26]:
obj2['s']


10

In [27]:
obj2['s']=10
obj2[['e','b','s']]

e    12
b     3
s    10
dtype: int64

In [28]:
obj2*3

e    36
b     9
s    30
w     6
dtype: int64

In [30]:
obj2[obj2>10]

e    12
dtype: int64

In [32]:
import numpy as np
np.exp(obj2)

e    162754.791419
b        20.085537
s     22026.465795
w         7.389056
dtype: float64

In [43]:
data= {'pen': 11, 'pencil':6, 'colors': 123}
obj =pd.Series(data)
obj

pen        11
pencil      6
colors    123
dtype: int64

In [36]:
sty=['pencil','pen','bag','colors']
obj3=pd.Series(data,index=sty)

obj3

pencil      6.0
pen        11.0
bag         NaN
colors    123.0
dtype: float64

In [37]:
pd.isnull(obj3)

pencil    False
pen       False
bag        True
colors    False
dtype: bool

In [44]:
#Data Frames

In [75]:
data= {'sty': ['pens','colors','pencils','erasers','glue','pointers','stickers'],
       'quantity': [10,122,23,43,34,5,43],
      'country': ['Pak','Germany','Turkey','Indonesia','India','Saudia','Canada']}
frame= pd.DataFrame(data)

In [76]:
frame

sty  quantity    country
0      pens        10        Pak
1    colors       122    Germany
2   pencils        23     Turkey
3   erasers        43  Indonesia
4      glue        34      India
5  pointers         5     Saudia
6  stickers        43     Canada

In [77]:
frame.index=['a','b','c','d','e','f','g']
frame

sty  quantity    country
a      pens        10        Pak
b    colors       122    Germany
c   pencils        23     Turkey
d   erasers        43  Indonesia
e      glue        34      India
f  pointers         5     Saudia
g  stickers        43     Canada

In [78]:
frame.head()

sty  quantity    country
a     pens        10        Pak
b   colors       122    Germany
c  pencils        23     Turkey
d  erasers        43  Indonesia
e     glue        34      India

In [79]:
pd.DataFrame(data,columns=['country','sty','quantity'])


country       sty  quantity
0        Pak      pens        10
1    Germany    colors       122
2     Turkey   pencils        23
3  Indonesia   erasers        43
4      India      glue        34
5     Saudia  pointers         5
6     Canada  stickers        43

In [80]:
data= {'sty': ['pens','colors','pencils','erasers','glue','pointers','stickers'],
       'quantity': [10,122,23,43,34,5,43],
      'country': ['Pak','Germany','Turkey','Indonesia','India','Saudia','Canada']}
frame= pd.DataFrame(data)

In [81]:
pd.DataFrame(data,columns=['country','sty','quanity'])

country       sty quanity
0        Pak      pens     NaN
1    Germany    colors     NaN
2     Turkey   pencils     NaN
3  Indonesia   erasers     NaN
4      India      glue     NaN
5     Saudia  pointers     NaN
6     Canada  stickers     NaN

In [82]:
frame.sty

0        pens
1      colors
2     pencils
3     erasers
4        glue
5    pointers
6    stickers
Name: sty, dtype: object

In [83]:
frame.country

0          Pak
1      Germany
2       Turkey
3    Indonesia
4        India
5       Saudia
6       Canada
Name: country, dtype: object

In [85]:
frame.loc[0]

sty         pens
quantity      10
country      Pak
Name: 0, dtype: object

In [86]:
frame['rating'] =10

In [87]:
frame

sty  quantity    country  rating
0      pens        10        Pak      10
1    colors       122    Germany      10
2   pencils        23     Turkey      10
3   erasers        43  Indonesia      10
4      glue        34      India      10
5  pointers         5     Saudia      10
6  stickers        43     Canada      10

In [99]:
frame['rating']=np.arange(7.)
frame

sty  quantity    country  rating
0      pens        10        Pak     0.0
1    colors       122    Germany     1.0
2   pencils        23     Turkey     2.0
3   erasers        43  Indonesia     3.0
4      glue        34      India     4.0
5  pointers         5     Saudia     5.0
6  stickers        43     Canada     6.0

In [102]:
val =pd.Series([1.3,2.4,6.7,3.5],index=[4,6,2,1])
frame['rating']=val
frame

sty  quantity    country  rating
0      pens        10        Pak     NaN
1    colors       122    Germany     3.5
2   pencils        23     Turkey     6.7
3   erasers        43  Indonesia     NaN
4      glue        34      India     1.3
5  pointers         5     Saudia     NaN
6  stickers        43     Canada     2.4

In [103]:
frame['eastern']=frame.country=='Pak'
frame

sty  quantity    country  rating  eastern
0      pens        10        Pak     NaN     True
1    colors       122    Germany     3.5    False
2   pencils        23     Turkey     6.7    False
3   erasers        43  Indonesia     NaN    False
4      glue        34      India     1.3    False
5  pointers         5     Saudia     NaN    False
6  stickers        43     Canada     2.4    False

In [104]:
del frame['eastern']
frame

sty  quantity    country  rating
0      pens        10        Pak     NaN
1    colors       122    Germany     3.5
2   pencils        23     Turkey     6.7
3   erasers        43  Indonesia     NaN
4      glue        34      India     1.3
5  pointers         5     Saudia     NaN
6  stickers        43     Canada     2.4

In [115]:
frame3.columns

Index(['pens', 'glue'], dtype='object')

In [111]:
frame3.T

india    pak
pens   34.0    NaN
glue    NaN  233.0

In [117]:
frame.values

array([['pens', 10, 'Pak', nan],
       ['colors', 122, 'Germany', 3.5],
       ['pencils', 23, 'Turkey', 6.7],
       ['erasers', 43, 'Indonesia', nan],
       ['glue', 34, 'India', 1.3],
       ['pointers', 5, 'Saudia', nan],
       ['stickers', 43, 'Canada', 2.4]], dtype=object)

In [118]:
frame3.values

array([[ 34.,  nan],
       [ nan, 233.]])